### ISSUE TITLE
Docstring with one quotation mark gets highlighted as it would have been written with three.

### ISSUE THREAD

**Issue by imsofi** [tree-sitter/tree-sitter-python#106]
If I make a docstring like
```py
def func(a, b):
    "This is my docstring."
    return True
```
It will give `"Th` and `ng"` different highlighting. As if it would have been written with 3 quotation marks.
```py
def func(a, b):
    """This is my docstring."""
    return True
```
The example doesn't follow the PEP conventions for docstrings. But should still have valid parsing.

**Comment by maxbrunsfeld** [comment]
Which highlighting are you referring to? Did you mean to open this issue on Neovim by any chance?

**Comment by imsofi** [comment]
Im using the [nvim-treesitter/nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) for highlighting in nvim yes.

Noticed that when using that extension it will create that behavior i described. And in their README they link this as the project for python highlighting. I might be in the wrong place if this is related to something nvim-treesitter is doing than this project itself.

**Comment by imsofi** [comment]
Yeah i seem to have gone to the wrong project. My bad. Ill open it there instead.
