### ISSUE TITLE
Syntax highlight error.

### ISSUE THREAD

**Issue by lkhphuc** [tree-sitter/tree-sitter-python#109]
<img width="250" alt="Screenshot 2021-06-15 at 11 17 38" src="https://user-images.githubusercontent.com/12573521/122036282-4c793880-cdcb-11eb-8a43-972c132d6108.png">

With treesitter enable, `in` in the loop `for x in X:` is not highlighted similar to `for`.

**Comment by RustemB** [comment]
same

**Comment by theHamsta** [comment]
Are you using Neovim or Atom? For Neovim please see https://github.com/nvim-treesitter/nvim-treesitter/issues/1563
