### ISSUE TITLE
trailing end-of-line comment not considered part of function body

### ISSUE THREAD

**Issue by orph** [tree-sitter/tree-sitter-python#113]
Similar to #112 - trailing end-of-line comment on the last line is not considered part of the function body.

<img width="698" alt="Screen Shot 2021-07-24 at 6 08 09 PM" src="https://user-images.githubusercontent.com/28068/126883002-53b06f17-309e-40b6-bdf9-87748a003d65.png">

**Comment by stsewd** [comment]
This is probably due that comment is included as "extras", but not as a statement

https://github.com/tree-sitter/tree-sitter-python/blob/24b530ca158d2782ea9046e756057a412e16b52f/grammar.js#L30-L33

so tree-sitter doesn't know where to put the node. Not really sure if it will be easy to fix, maybe including the comment node as an expression in addition to extras.

**Comment by maxbrunsfeld** [comment]
It's because the `dedent` external token is being returned at the wrong time (before the comment, when it should be after the commit).
