### ISSUE TITLE
Include \ in the syntax tree

### ISSUE THREAD

**Issue by Wilfred** [tree-sitter/tree-sitter-python#118]
Currently the `\` is ignored in the following:

```
from x \
    import y
```

For [difftastic](https://github.com/wilfred/difftastic) I'd really like to be able to see this `\` operator in the parse tree. It looks like `\` is currently in `extras` and therefore ignored.

https://github.com/tree-sitter/tree-sitter-python/blob/d6210ceab11e8d812d4ab59c07c81458ec6e5184/grammar.js#L28-L31

As a result, tree-sitter-python accepts the code sample even if it's missing the `\`, e.g.

```
from x
    import y
```

I can't see any way this can lead to incorrect parses of valid code, but it would be nice to have `\` included.

**Comment by stsewd** [comment]
This is exposed as `(line_continuation)` now.

**Comment by stsewd** [comment]
This issue can be closed now
