### ISSUE TITLE
`await` not parse properly after `in`

### ISSUE THREAD

**Issue by WhyNotHugo** [tree-sitter/tree-sitter-python#119]
In this specific example, the `await` keyword isn't being properly highlighted:

```python
async def region_exists(region: str) -> bool:
    return region in await all_regions()
#                    ^^^^^ This keyword is not highlighted properly
```

Huh, it seems that GitHub also doesn't highlight it properly.

**Comment by theHamsta** [comment]
> Huh, it seems that GitHub also doesn't highlight it properly.

Because it is using tree-sitter-python? Please report it in their repo.

**Comment by obataku** [comment]
>Huh, it seems that GitHub also doesn't highlight it properly.

[github/linguist](https://github.com/github/linguist/blob/master/vendor/README.md) uses tree-sitter-python for its highlighting
