### ISSUE TITLE
Function definition and function call

### ISSUE THREAD

**Issue by silenc3r** [tree-sitter/tree-sitter-python#127]
How do I assign different color to function definition and function call?

**Comment by stsewd** [comment]
This should be done by your editor/colorscheme, you can take a look at the queries from neovim

https://github.com/nvim-treesitter/nvim-treesitter/blob/575f5a4b1fcb60c1ac4f560c46a5171454d674ca/queries/python/highlights.scm#L47-L52

https://github.com/nvim-treesitter/nvim-treesitter/blob/575f5a4b1fcb60c1ac4f560c46a5171454d674ca/queries/python/highlights.scm#L97-L98
