### ISSUE TITLE
How to build a tree-sitter-python.wasm that works?

### ISSUE THREAD

**Issue by pcdeadeasy** [tree-sitter/tree-sitter-python#133]
I am having issues when I generate the wasm file using the instructions on: https://github.com/tree-sitter/tree-sitter/blob/master/lib/binding_web/README.md. I am running the code on a windows machine. The call to Parser.Language.load("tree-sitter-python.wasm") gives these errors:

Assertion failed: undefined
c:\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js:5
**rejected promise not handled within 1 second: RuntimeError**: abort(Assertion failed: undefined). Build with -s ASSERTIONS=1 for more info.
c:\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js:5
stack trace: RuntimeError: abort(Assertion failed: undefined). Build with -s ASSERTIONS=1 for more info.

**Comment by wenkokke** [comment]
Build web-tree-sitter in debug mode using:
```make
node_modules/web-tree-sitter:
	git clone --depth 1 --branch $(TREE_SITTER_VERSION) https://github.com/tree-sitter/tree-sitter.git tmp/tree-sitter
	cp tree-sitter.patch tmp/tree-sitter/
	cd tmp/tree-sitter\
		&& git apply tree-sitter.patch\
		&& ./script/build-wasm --debug
	mkdir -p node_modules/web-tree-sitter
	cp tmp/tree-sitter/LICENSE node_modules/web-tree-sitter
	cp $(addprefix tmp/tree-sitter/lib/binding_web/,$(WEB_TREE_SITTER)) node_modules/web-tree-sitter
	rm -rf tmp/tree-sitter
```
This enables `ASSERTIONS=1`. Then reload tree-sitter-python.wasm using this version of web-tree-sitter, and you’ll be able to see the error message. If it complains about a missing symbol, add it to tree-sitter/lib/binding_web/exports.json, prefixed with an underscore, and recompile web-tree-sitter. Iterate until, hopefully, you have a working version.

**Comment by wenkokke** [comment]
(I think this issue might be fixed already, but I’m commenting anyway for documentation purposes.)

**Comment by verhovsky** [comment]
@wenkokke I tried to follow your instructions:

- what is `tree-sitter.patch`?
- you reference variables with `$TREE_SITTER_VERSION`, not `$(TREE_SITTER_VERSION)`
- what is `$WEB_TREE_SITTER`

I got `$TREE_SITTER_VERSION` by going to https://github.com/tree-sitter/tree-sitter/releases and copying `v0.20.2`

**Comment by wenkokke** [comment]
> @wenkokke I tried to follow your instructions:
> 
> * what is `tree-sitter.patch`?
> * you reference variables with `$TREE_SITTER_VERSION`, not `$(TREE_SITTER_VERSION)`
> * what is `$WEB_TREE_SITTER`
> 
> I got `$TREE_SITTER_VERSION` by going to https://github.com/tree-sitter/tree-sitter/releases and copying `v0.20.2`

- The tree-sitter.patch is whatever changes you want to make, probably additions to exports.json.
- It’s a Makefile rule, not a Shell script.
- WEB_TREE_SITTER the list of files in the web-tree-sitter package, minus LICENSE.

All in all, this is just a rule to patch web-tree-sitter locally.
