### ISSUE TITLE
NEWLINE, INDENT, DEDENT tokens for pretty-printing

### ISSUE THREAD

**Issue by brozi** [tree-sitter/tree-sitter-python#136]
Hello,
I'm working on something on a project that requires to work with the AST to do some modifications and also to pretty-print the AST (i.e. transform the AST into working source code). Right now, I can print all the tokens easily by searching the tree and printing all the leafs but I'm missing all the newlines, indentations, and dedentations, which are necessary in python. In the python 3 grammar, I can see that NEWLINE, INDENT and DEDENT tokens are defined but I cannot find them in the AST. Is it possible access the indentation and newline tokens in the AST?

**Comment by ethan-leba** [comment]
I'm also interested in this. This could be fixed by unhiding the tokens, what do the maintainers think of this?

**Comment by theHamsta** [comment]
@kyazdani42

**Comment by amaanq** [comment]
Un-hiding them would pollute the tree - that being said a mechanism to fetch hidden nodes might be useful upstream
