### ISSUE TITLE
Is it possible to create a three address code IR from `tree.rootNode`?

### ISSUE THREAD

**Issue by genderev** [tree-sitter/tree-sitter-python#139]
I've been attempting to use `tree-sitter-python` as the parser for a Python interpreter but I'm not sure whether I am attempting something that is impossible.

Is there a recommended way to incrementally go through each node of the parse tree? 
I'm also very confused about how queries work. I want to be able to write a query that says - somehow - return the right and left hand sides of an `expression_statement` or `call`, but I'm not sure how.

**Comment by amaanq** [comment]
I'm not sure what you mean by "three address code IR", and your first question, IIUC, is an easy yes, you can walk the syntax tree. If you have a specific code snippet that you need help querying, that'd be helpful. But to put it simply, you'd do something like this for querying:

```scm
(call
  function: (_) @left
  arguments: (_) @right
)
```
