### ISSUE TITLE
Feature request: Syntax highlighting for using pipe as a union operator

### ISSUE THREAD

**Issue by lmburns** [tree-sitter/tree-sitter-python#149]
In [`PEP 604`](https://www.python.org/dev/peps/pep-0604/), the pipe symbol (`|`) was implemented as a `Union` operator and when using it in cases such as the following, the types aren't recognized to be highlighted.

```python
isinstance(5, int | str)

# or

def f(s: int | float) -> None:
    print(s + 1)
```

**Comment by cjwcommuny** [comment]
As far as I know, this issue has nothing to do with tree-sitter-python. It's the plugin's responsibility to properly highlighting it.

**Comment by stsewd** [comment]
That code is parsed correctly by grammar. As mentioned, if you want to have those highlighted differently, you can do that by using a query.
