### ISSUE TITLE
Pattern matching parser errors with assignment expressions

### ISSUE THREAD

**Issue by GBeauregard** [tree-sitter/tree-sitter-python#150]
The following code snippet parses with errors after pattern matching was merged. In particular, this causes the `:=` to be mishighlighted in two colors with `nvim-treesitter`. 
```python
def duration(timestamp: str | float | int) -> float:
    """Processes ffmpeg duration string into time in seconds.

    https://ffmpeg.org/ffmpeg-utils.html#Time-duration
    """
    time = str(timestamp)
    if match := re.fullmatch(r"(-)?(\d+:)?\d?\d:\d\d(\.\d*)?", time, flags=re.ASCII):
        return sum(
            s * abs(float(t)) for s, t in zip([1, 60, 3600], reversed(time.split(":")))
        ) * (-1 if match.group(1) else 1)
    if match := re.fullmatch(r"(-?(?:\d+\.?\d*|\.\d+))([mu]?s)?", time, flags=re.ASCII):
        val = float(match.group(1))
        if match.group(2) == "ms":
            val /= 1000
        elif match.group(2) == "us":
            val /= 1_000_000
        return val
    raise ValueError(f"Invalid ffmpeg duration: {timestamp!r}")
```

Changing the name of the variable away from match fixes the parsing. This is typical pattern usage for assignment expressions (walrus), and examples that fail to parse in the same way can be found [in PEP 572](https://www.python.org/dev/peps/pep-0572/#capturing-condition-values). Note also `black` will remove parentheses here if you try to add them.

**Comment by theHamsta** [comment]
Probably the same hack to make `match` work with assignment expressions would also work with `named_assignement` (adding `alias("match", $.identifier)`. I have to try it out.
