### ISSUE TITLE
Strings missing values.

### ISSUE THREAD

**Issue by rkirchofer** [tree-sitter/tree-sitter-python#151]
How can I get the values of strings?
I want to use tree-sitter from clojure to parse python but I wasn't able to get the [java bindings](https://github.com/serenadeai/java-tree-sitter) to work. I'm happy to parse the xml but it's missing data that I need.

```
$ cat test.py
"thing" is not None
$ tree-sitter parse --xml --quiet test.py
<module>
  <expression_statement>
    <comparison_operator>
      <string>""</string>
isnot
      <none>None</none>
</comparison_operator>
</expression_statement>
</module>
```
Thanks!

**Comment by stsewd** [comment]
https://github.com/tree-sitter/tree-sitter-python/pull/114 could help with this, otherwise you'll need to get that information manually (but doesn't look like the generated xml includes information about the position of the nodes).

**Comment by rkirchofer** [comment]
Thanks.
