### ISSUE TITLE
Support docblocks in Grammar

### ISSUE THREAD

**Issue by ce-bo** [tree-sitter/tree-sitter-python#154]
Hi,

would it be possible to support python docblocks?
https://www.python.org/dev/peps/pep-0257/

Thanks!

**Comment by stsewd** [comment]
If you mean parsing the docstring as rst/markdown, you can do that with injections (https://tree-sitter.github.io/tree-sitter/syntax-highlighting#language-injection), for example, if you are using neovim, you can do this:

```scm
(expression_statement (string (string_content) @rst))
```
