### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by jirutka** [tree-sitter/tree-sitter-python#155]
Can you please tag a new version? I’m maintainer of this package in Alpine Linux and just got a request to update to the latest revision in master branch because “Latest tag doesn't work with modern nvim-treesitter”.

**Comment by bcmyers** [comment]
I'm using this in `bazel` and pulling in a version based on a git commit tag is painful there (although there is a workaround for it). I'd love to eliminate my workaround though; so it would really be a big help if you could cut another version please.

**Comment by wkordalski** [comment]
I'm using the [tree-sitter-python@0.19.1](https://crates.io/crates/tree-sitter-python) Rust crate.
I would like to move to `tree-sitter@0.20`,
so I would also be interested in a crate containing grammar for the newer tree-sitter.

**Comment by wkordalski** [comment]
I suppose this issue can be closed as new (0.20) version was tagged, and published to crates.io and npmjs.com
