### ISSUE TITLE
does the `not` parse correctly?

### ISSUE THREAD

**Issue by NorthIsUp** [tree-sitter/tree-sitter-python#158]
In the tests there is a section `not a == b or c == d` and this seems to be parsed as `not ((a == b) or (c == d))` where python would parse this as `(not (a == b)) or (c == d)`.

So bug or featrue?

```
In [6]: not 2 == 1
Out[6]: True

In [7]: 2 == 1
Out[7]: False
```

here is the test section I'm referencing:
```
================================================================================
Comparison operators
================================================================================

a < b <= c == d >= e > f
not a == b or c == d

--------------------------------------------------------------------------------

(module
  (expression_statement
    (comparison_operator
      (identifier)
      (identifier)
      (identifier)
      (identifier)
      (identifier)
      (identifier)))
  (expression_statement
    (not_operator
      (boolean_operator
        (comparison_operator
          (identifier)
          (identifier))
        (comparison_operator
          (identifier)
          (identifier))))))
 ```

**Comment by cedricrupb** [comment]
Same problem here. It seems that the precedences are defined quite different than the precedence order
of [Python](https://docs.python.org/3/reference/expressions.html#operator-precedence).

Typically, I would expect that operator have the following precedence (in descending order):
```
parenthesis
call
...
comparison
not
and 
or
...
```

However, it seems like the `grammar.js` defines the order as [follows](https://github.com/tree-sitter/tree-sitter-python/blob/78c4e9b6b2f08e1be23b541ffced47b15e2972ad/grammar.js#L10):
```
call
...
and 
or
comparison
not
parenthesis
...
```

Is there a reason for that?

**Comment by cedricrupb** [comment]
Interestingly enough, Issue #119 might be related to this (`await` higher precedence than `comparison`).
