### ISSUE TITLE
`not in` vs `[not, in]`

### ISSUE THREAD

**Issue by NorthIsUp** [tree-sitter/tree-sitter-python#159]
Python's ast has `NotIn` as a node, should we also have it be a single node?

**Comment by cedricrupb** [comment]
Would be interesting to then also include the `IsNot` node!

**Comment by stsewd** [comment]
They are exposed as anonymous nodes now

https://github.com/tree-sitter/tree-sitter-python/blob/7c8930b6388b5590ebef248853f144185a9eda1d/grammar.js#L709-L711

ref https://github.com/tree-sitter/tree-sitter-python/pull/190

Just keep in mind that there is a bug in tree-sitter, that makes this two nodes `"not int" "not in"` :/ https://github.com/tree-sitter/tree-sitter/issues/2299

**Comment by shaohme** [comment]
"not in" is not recognized correctly in latest Emacs+tree-sitter either. Looking forward to it 🙂
