### ISSUE TITLE
`print()` as expression, or statement?

### ISSUE THREAD

**Issue by rewinfrey** [tree-sitter/tree-sitter-python#16]
In Python 2, `print()` prints: `()`.

In Python 3, `print()` prints ``.

Python 2 treats `print()` as a print statement for the empty tuple.

Python 3 treats `print()` as an expression with no arguments.

I may be mistaken, but I believe we have to make a fundamental decision about how the Python grammar will interpret this, because we do not differentiate between Python versions.

@maxbrunsfeld, my thought is to parse `print()` according to the native AST produced by Python 3. My simple mind thinks, "Python 3 code will likely outlive Python 2 code." What would you suggest?

Current behavior on master parses this according to Python 2:

```
(print_statement (tuple))
```

I'd propose instead:

```
(expression_statement (call (identifier) (argument_list)))
```

**Comment by maxbrunsfeld** [comment]
Yeah, ideally, our parser would make the same guess that an educated human would, if they didn't know whether a given source file is going to be run with python 2 or python 3.

I would say that if I saw `print` followed by parentheses in a python source file, I would assume that it was python 3. In python 2, it seems uncommon that you'd want to print a tuple, as opposed to printing the elements individually.

**Comment by maxbrunsfeld** [comment]
This was addressed in https://github.com/tree-sitter/tree-sitter-python/commit/60ac93728d35ba87392b2750cbb04b49a2df17db
