### ISSUE TITLE
Incorrect parsing of (some) expressions within f-string interpolations

### ISSUE THREAD

**Issue by bm424** [tree-sitter/tree-sitter-python#164]
[Sorry for the long post, thought best to give as much detail on this one as possible given it's quite niche]

**The problem**

In the following code snippet, both the `if` statement's test _and_ the f-string's interpolation body are parsed as `named_expression`:
```python
if x := 5:
    f"{x := 5}"
```
Named expressions (and, incidentally, lambda expressions) aren't allowed inside interpolations (from the python docs [here](https://docs.python.org/3/reference/lexical_analysis.html#formatted-string-literals)):
> Expressions in formatted string literals are treated like regular Python expressions surrounded by parentheses, with a few exceptions. An empty expression is not allowed, and both [lambda](https://docs.python.org/3/reference/expressions.html#lambda) and assignment expressions := must be surrounded by explicit parentheses.

The second `x := 5` should be interpreted as an interpolation with an identifier on the left and a format specifier (`=5`) on the right.

This is definitely an edge-case bug, but took me a day to identify and kind-of fix.

**Possible fix**

I have this working in a fork, but not sure it's the best approach.

Interpolations can't contain named expressions, nor can they contain, for example, boolean operations which themselves contain named expressions. For example, the following is illegal:
```python
f"{a := 3 or b := 0}"
```
So, for every type of expression that _can_ appear in an interpolation (comparison, not operator, boolean operator, await, conditional expressions, and all the "`primary_expression`s", create an interpolation-friendly duplicate, which can only themselves contain interpolation-friendly expressions.

```js
    _interpolation_expression: $ => choice(
      $.comparison_operator,
      alias($._interpolation_not_operator, $.not_operator),
      alias($._interpolation_boolean_operator, $.boolean_operator),
      alias($._interpolation_await, $.await),
      $.primary_expression,
      alias($._interpolation_conditional_expression, $.conditional_expression)
    ),

    interpolation: $ => seq(
      '{',
      $._interpolation_expression,
      optional('='),
      optional($.type_conversion),
      optional($.format_specifier),
      '}'
    ),
```
with, for example, the interpolation not operator defined as
```js
    _interpolation_not_operator: $ => prec(PREC.not, seq(
      'not',
      field('argument', $._interpolation_expression)
    )),
```

**Comment by amaanq** [comment]
PR welcome, as long as it doesn't increase state count too much. Tree-Sitter is permissive on purpose for that reason

**Comment by kaddkaka** [comment]
I saw some error on f-strings writing f-strings today. It's our related to this issue? Also, are nested f-strings even allowed?

**Comment by amaanq** [comment]
> also this ![image](https://private-user-images.githubusercontent.com/71744831/321679081-6bb33cc2-b0b2-47d2-8db5-15ed4780effa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4ODUzNDksIm5iZiI6MTcxMjg4NTA0OSwicGF0aCI6Ii83MTc0NDgzMS8zMjE2NzkwODEtNmJiMzNjYzItYjBiMi00N2QyLThkYjUtMTVlZDQ3ODBlZmZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDAxMjQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2YTA4ZWY0YzE2NWMzZjk0ZTRiNDFiNjlmNzk1MjQ3MjNhMTY2YTRlYzYyNGFmYmIxZmIyNTVkNjk3NGJjMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2Q2TJgYlZg6UjM3EP_2vlu1-k2BqkZ_cc1cgOosLPZc)
> 
> edit: ignore the red dot its a mistake in the image

this is an unclear example
