### ISSUE TITLE
String/byte prefix

### ISSUE THREAD

**Issue by firai** [tree-sitter/tree-sitter-python#167]
What's the best way to separate out the string/byte prefixes (such as `f`, `r`, `u` and `b` before the quotes) from the string itself (maybe as a sub-node)? I understand from the Neovim TSPlayground plugin and the playground website that the prefixes are currently directly part of the string node.

**Comment by amaanq** [comment]
At the moment you really can't without some weird injection logic, they're a part of the string_start node.

**Comment by rj-lee** [comment]
In case this helps anyone, I was able to achieve this with the following queries:

```scm
(
  (string
    (string_start) @keyword
  )
  (#match? @keyword "^([frub]|fr|rf)[\"']$")
  (#offset! @keyword 0 0 0 -1)
)

(
  (string
    (string_start) @keyword
  )
  (#match? @keyword "^([frub]|fr|rf)[\"']{3}$")
  (#offset! @keyword 0 0 0 -3)
)
```
