### ISSUE TITLE
Python docstring are recognised as string

### ISSUE THREAD

**Issue by sabah1994** [tree-sitter/tree-sitter-python#168]
![ts_python](https://user-images.githubusercontent.com/73726199/174411122-4f89c699-a77f-474a-aefd-e77b8c4448d9.png)

Hi, 
Docstrings are recognised as String, could you change so they are rightly recognised as comment. 

Thank you

**Comment by stsewd** [comment]
Hi, docstrings are strings! Looks like you are using neovim, so what you probably want is to add an injections.scm file like this

https://github.com/stsewd/dotfiles/blob/1adbb2e4dadb3c958c8a745f31b24c46052d7427/config/nvim/after/queries/python/injections.scm

(replacing `@rst` with `@comment`)


See https://github.com/nvim-treesitter/nvim-treesitter#adding-queries.

**Comment by sabah1994** [comment]
hey,
Thanks for the prompt reply.
I did as you said and it made no difference. 

Text in .config/nvim/after/queries/python/injections.scm
; Module docstring
((module . (expression_statement (string) @comment))
 (#offset! @comment 0 3 0 -3))

; Class docstring
((class_definition
  body: (block . (expression_statement (string) @comment)))
 (#offset! @comment 0 3 0 -3))

; Function/method docstring
((function_definition
  body: (block . (expression_statement (string) @comment)))
 (#offset! @comment 0 3 0 -3))

; Attribute docstring
(((expression_statement (assignment)) . (expression_statement (string) @comment))
 (#offset! @comment 0 3 0 -3))

**Comment by stsewd** [comment]
@sabah1994 do you have the comment parser installed? `:TSInstall comment`

**Comment by sabah1994** [comment]
@stsewd 
Sorry I wasn't aware I needed to, started with tree-sitter few hours ago.

After installing, TODO highlighted which is great but rest of the docstring is still the same.
![comment](https://user-images.githubusercontent.com/73726199/174415739-2981fd0d-f169-4e9f-8d8c-bc63bbe750fd.png)

**Comment by stsewd** [comment]
If you want to change the color, then you need to create a `queries/python/highlights.scm` with something like

```
; Module docstring
(module . (expression_statement (string) @comment))

; Class docstring
(class_definition
  body: (block . (expression_statement (string) @comment)))

; Function/method docstring
(function_definition
  body: (block . (expression_statement (string) @comment)))

; Attribute docstring
((expression_statement (assignment)) . (expression_statement (string) @comment))
```

**Comment by sabah1994** [comment]
Thank you so much, it worked.

**Comment by sabah1994** [comment]
hey @stsewd 
Queries which you helped me add to recognise docstrings as comments have stopped working. I recently upgraded to nvim0.8, not sure if that could have impacted it.
![Screenshot from 2022-10-30 10-14-06](https://user-images.githubusercontent.com/73726199/198873424-8946122d-2f0b-40d9-993f-60a09fb566f7.png)

**Comment by stsewd** [comment]
@sabah1994 you need to add `; extends` at the top of your query file, see `:h treesitter-query-modeline` https://github.com/neovim/neovim/issues/14090#issuecomment-1240357210.

Also, this repo is for the tree-sitter python parser, for the neovim integration you should open issues at https://github.com/nvim-treesitter/nvim-treesitter

**Comment by sabah1994** [comment]
it worked. thanks again
