### ISSUE TITLE
How to add different highlight for __dunder__ methods

### ISSUE THREAD

**Issue by ArnoldWolfstein** [tree-sitter/tree-sitter-python#169]
Hi there,
How can we add different highlight for `__dunder__` methods a.k.a. magic methods? Is there a *TS highlight group* for that?
I know there is `pythonTSConstructor` for `__init__` method that I can customize, but I couldn't figure out for other *magic* methods.

**Comment by stsewd** [comment]
Hi, they are currently under the `TSConstBuiltin` hl group,

https://github.com/nvim-treesitter/nvim-treesitter/blob/5c364707442965ae52a1ac89c359080e32958445/queries/python/highlights.scm#L16-L17

Also, you should ask this at the https://github.com/nvim-treesitter/nvim-treesitter repo.

**Comment by ArnoldWolfstein** [comment]
Sorry my later reply.

No, it's not `TSConstBuiltin`. It appears that it's for const/var like `__name__`. 
This regex matches with dunder methods as well, but they are overwritten by `TSMethod`: [image]

Oh, ok, I thought opening here since specific to python would be more appropriate. Closing this then.

P.S:
Lukas gave some insights in this thread: [thread]


[image]: https://gist.githubusercontent.com/ArnoldWolfstein/da195fe1348a47177d02833aeb7dcf9b/raw/e46951fe87e606a561462274b772c08601dc4771/image.png
[thread]: https://www.reddit.com/r/neovim/comments/vf42lo/comment/icwlcqo/?utm_source=share&utm_medium=web2x&context=3
