### ISSUE TITLE
Error in build with tree-sitter-cli 0.7.3: "Unknown rule type: ALIAS"

### ISSUE THREAD

**Issue by gnprice** [tree-sitter/tree-sitter-python#17]
In a fresh clone, if I run `npm install` and then `npm run build`, I get the following error:
```
$ npm run build

> tree-sitter-python@0.2.0 build /tmp/tree-sitter-python
> tree-sitter generate && node-gyp build

Error: Invalid choice member: Unknown rule type: ALIAS

npm ERR! Linux 4.9.0-3-amd64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! node v6.11.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! tree-sitter-python@0.2.0 build: `tree-sitter generate && node-gyp build`
npm ERR! Exit status 1
[...]
```

Similarly if I simply run `node_modules/.bin/tree-sitter generate`, I get
```
Error: Invalid choice member: Unknown rule type: ALIAS
```

If after the `npm install` I add `npm install tree-sitter-cli@0.7.1`, then `npm run build` works great. Ditto with 0.7.2.

**Comment by maxbrunsfeld** [comment]
@gnprice Yeah, thanks for the report. Version 0.7.3 was an accidental publish; pushing out a new 0.7.4 release now so you don't have to do this.

**Comment by gnprice** [comment]
Confirmed, works now -- thanks!
