### ISSUE TITLE
Syntax error detected too early

### ISSUE THREAD

**Issue by andrescodas** [tree-sitter/tree-sitter-python#171]
The syntax error related to the unbalanced parenthesis is detected for the whole function definition, but it could be marked only on the last line

![image](https://user-images.githubusercontent.com/164282/174895919-e9fbd43b-393c-40b4-a0ce-a2bb4d501adb.png)

**Comment by stsewd** [comment]
Code from master recovers better here, for your example:

```python
def test():
    assert True
    assert foo(123,
```

```scm
(module [0, 0] - [3, 0]
  (function_definition [0, 0] - [2, 19]
    name: (identifier [0, 4] - [0, 8])
    parameters: (parameters [0, 8] - [0, 10])
    body: (block [1, 4] - [2, 19]
      (assert_statement [1, 4] - [1, 15]
        (true [1, 11] - [1, 15]))
      (ERROR [2, 4] - [2, 19]
        (identifier [2, 11] - [2, 14])
        (integer [2, 15] - [2, 18])))))
```

I think we can close this.
