### ISSUE TITLE
Using tree-sitter-python as a basis for tree-sitter-snakemake?

### ISSUE THREAD

**Issue by matthuska** [tree-sitter/tree-sitter-python#174]
I'd like to get tree sitter working for [Snakemake](https://snakemake.readthedocs.io/en/stable/) workflow files. The workflows are defined in a language that is essentially python + a bit of extra stuff (grammar for the extra stuff is [here](https://snakemake.readthedocs.io/en/stable/snakefiles/writing_snakefiles.html#grammar)).

Do you have any advice for how the tree-sitter project handles these kinds of "sub-languages" that are based of existing languages? It seems like it would make sense to use the tree-sitter-python code as a starting point, and add the Snakemake-specific grammar rules and additional tests, and then track any changes to this repo and have them incorporated. Does that sound reasonable? What is the best practice for properly crediting the work done on the original code and the original authors?

**Comment by stsewd** [comment]
You can take a look at the CPP grammar https://github.com/tree-sitter/tree-sitter-cpp/blob/0e7b7a02b6074859b51c1973eb6a8275b3315b1d/grammar.js#L13, it extends the C grammar.

**Comment by amaanq** [comment]
See https://github.com/osthomas/tree-sitter-snakemake
