### ISSUE TITLE
Module node error with nested blocks

### ISSUE THREAD

**Issue by ghfarzad** [tree-sitter/tree-sitter-python#175]
I ran into below issue when parsing python code with tree-sitter.

For below simple nested blocks, tree sitter gives an error node for the while block.

![image](https://user-images.githubusercontent.com/3599669/195143224-3e7da717-7496-40fc-81d4-eb07d910d563.png)

Increasing the depth of nested blocks as below, however, would turn the whole module node into an error node

![image](https://user-images.githubusercontent.com/3599669/195142085-abfb78fb-9c59-4b1b-8dab-41652d5a5a0b.png)

Perhaps, it's related to #171

**Comment by stsewd** [comment]
Hi, your examples are parsed like this now with the code from master:

```python
while 1:
    if 1
```

```scm
(module [0, 0] - [2, 0]
  (while_statement [0, 0] - [1, 8]
    condition: (integer [0, 6] - [0, 7])
    (ERROR [1, 4] - [1, 8]
      (integer [1, 7] - [1, 8]))
    body: (block [1, 8] - [1, 8])))
```

```python
while 1:
    if 1:
        for a in []:
            if 1
```

```scm
(module [0, 0] - [4, 0]
  (while_statement [0, 0] - [3, 16]
    condition: (integer [0, 6] - [0, 7])
    body: (block [1, 4] - [3, 16]
      (if_statement [1, 4] - [3, 16]
        condition: (integer [1, 7] - [1, 8])
        consequence: (block [2, 8] - [3, 16]
          (for_statement [2, 8] - [3, 16]
            left: (identifier [2, 12] - [2, 13])
            right: (list [2, 17] - [2, 19])
            (ERROR [3, 12] - [3, 16]
              (integer [3, 15] - [3, 16]))
            body: (block [3, 16] - [3, 16])))))))
```

So the problem reported seems to be fixed.

**Comment by amaanq** [comment]
The playground uses outdated versions iirc
