### ISSUE TITLE
Parse error when encountering raw formatted strings with escape sequences in them

### ISSUE THREAD

**Issue by patrickt** [tree-sitter/tree-sitter-python#179]
As of HEAD, this does not parse: `rf"\{123}”`. Removing the backslash or changing the prefix to either `r` or `f` or neither (but not both)

Found via a failure in sqlalchemy.

**Comment by patrickt** [comment]
Found in pandas too: https://github.com/pandas-dev/pandas/blob/main/pandas/io/parsers/python_parser.py#LL1241C9-L1241C65

**Comment by tausbn** [comment]
This should be fixed as of #184.
