### ISSUE TITLE
Incorrect parse tree for comparison operator

### ISSUE THREAD

**Issue by rewinfrey** [tree-sitter/tree-sitter-python#2]
Given the expression:

`assert isinstance(copy2, variables.Variable)`

The parse tree generated is:

```shell
(module [0, 0] - [1, 0]
  (expression_statement [0, 0] - [0, 44]
    (comparison_operator [0, 0] - [0, 44]
      (identifier [0, 0] - [0, 6])
      (call [0, 9] - [0, 44]
        (identifier [0, 9] - [0, 17])
        (identifier [0, 18] - [0, 23])
        (attribute [0, 25] - [0, 43]
          (identifier [0, 25] - [0, 34])
          (identifier [0, 35] - [0, 43]))))))
```

The `comparison_operator` rule contains `in`, and it appears the `isinstance` call is being incorrectly labeled as a `comparison_operator` because it's matching `in`. Is that what you think is happening @maxbrunsfeld?

**Comment by maxbrunsfeld** [comment]
I think the problem is that the grammar did not include `assert` statements, so `tree-sitter` was parsing this code as if `assert` was just a normal identifier. It was then interpreting the word `is` in `isinstance` as a relational operator, as if the code was

```python
a is instance(copy2, variables.Variable)
```

I had an un-pushed commit adding `assert` statements, so I just pushed that. Maybe it will fix this issue.

**Comment by rewinfrey** [comment]
@maxbrunsfeld ah thanks so much! I didn't think of `assert` as a Python keyword, instead seeing it in test files assuming it was a method call for a test framework used by tensorflow. That said, my Python knowledge is very limited 😅 .

Given the statement:

`assert isinstance(copy2, variables.Variable)`

The `assert_statement` rule now correctly parses this as:

```shell
(module [0, 0] - [1, 0]
  (assert_statement [0, 0] - [0, 44]
    (call [0, 7] - [0, 44]
      (identifier [0, 7] - [0, 17])
      (identifier [0, 18] - [0, 23])
      (attribute [0, 25] - [0, 43]
        (identifier [0, 25] - [0, 34])
        (identifier [0, 35] - [0, 43])))))
```

All looks 👍
