### ISSUE TITLE
Migrate scanner to C

### ISSUE THREAD

**Issue by lewis6991** [tree-sitter/tree-sitter-python#206]
Hey, we are thinking about bundling this parser into Neovim, however one of the concerns is raising our build requirements to include C++. (https://github.com/neovim/neovim/pull/22458)

I've looked at the code and it would be quite straightforward to port to C. We've already done this for https://github.com/MDeiml/tree-sitter-markdown/issues/84 which has a larger scanner.

Is this something that would be accepted?

Duplicate issue on tree-sitter-bash: https://github.com/tree-sitter/tree-sitter-bash/issues/149

**Comment by ahlinc** [comment]
I'd suggest to take Haskell's [scanner](https://github.com/tree-sitter/tree-sitter-haskell/blob/master/src/scanner.c) as a reference.
