### ISSUE TITLE
Expose real string quotes in a tree to don't mislead

### ISSUE THREAD

**Issue by ahlinc** [tree-sitter/tree-sitter-python#210]
In a current grammar definition:
```js
    string: $ => seq(
      field('prefix', alias($._string_start, '"')),
      repeat(choice(
        field('interpolation', $.interpolation),
        field('string_content', $.string_content)
      )),
      field('suffix', alias($._string_end, '"'))
    ),
```
Aliases hide actual tokens like `'''` and `"""`:
```js
alias($._string_start, '"')
alias($._string_end, '"')
```

**Comment by tausbn** [comment]
I'm not sure I see what the problem is. The exposed token is `"`, but the underlying _source text_ has the full original token.

For instance, the following query can be used to match only strings delimited with triple (single) quotes:
```
(
  (string "\"" @quote) @str
  (#match? @quote "'''")
)
```

**Comment by ahlinc** [comment]
> The exposed token is ", but the underlying source text has the full original token.

Yes, the token has a correct range that allows to access a correct piece in an original input.
But with predicates that is much slower because they work outside of a query engine as post filtering and require access to an input.

If there will be correct terminals then queries like bellow would work without predicates:
```scheme
; Strings with only triple single quotes
  (string "'''" @quote) @str

; Strings with triple quotes
  (string [ "'''" "\"\"\"" ] @quote) @str
```

And in a visual tree representation there will be no misunderstanding:
<details>

![Screenshot from 2023-03-11 19-07-50](https://user-images.githubusercontent.com/14666676/224502340-fc0d9f37-34ee-43b2-83c3-93a5b172a232.png)
</details>

I think it should become a _bad practice_ to hide actual terminals that define syntax structure and replace them to something another. But for now this exist in this grammar for historical reasons.

**Comment by andymass** [comment]
Have a similar problem, I'm looking for a query to target _only_ the quote characters, not the entire string.  For many languages this works with (_ "\"" "\"") or similar, but not for python.  Is there an easy query like this?
