### ISSUE TITLE
Missing git tag for v0.20.2

### ISSUE THREAD

**Issue by jirutka** [tree-sitter/tree-sitter-python#216]
There’s [0.20.2](https://crates.io/crates/tree-sitter-python/0.20.2) on crates.io, but the latest tag in this repository is v0.20.0.

**Comment by nekopsykose** [comment]
0.20.3 has a tag now, so this is resolved for future

**Comment by amaanq** [comment]
I pushed it anyways, but yep 0.20.3 is out
