### ISSUE TITLE
3.12 "`type`" soft keyword (PEP 0695)

### ISSUE THREAD

**Issue by johannesrld** [tree-sitter/tree-sitter-python#236]
(Per [pep0695](https://peps.python.org/pep-0695/))

Python 3.12 (Upcoming) introduced a new soft keyword called type which allows you to do something like this: 
```python
# A non-generic type alias
type IntOrStr = int | str
# A generic type alias
type ListOrSet[T] = list[T] | set[T]
```
(It also introduces generics syntax for things like functions and classes but thats probably better left to another issue)

**Comment by amaanq** [comment]
Added on master
