### ISSUE TITLE
Parameter highlight group doesn't capture references in body

### ISSUE THREAD

**Issue by CipherJay** [tree-sitter/tree-sitter-python#247]
I use a highlighting color for parameters to help with readability. Rust and many other languages will highlight the parameter inside the parentheses the same color as when it is referenced in the body of the function. This doesn't seem to work with Python. Maybe you know of a quick fix to this issue since you've written the code and know how it all works. I thought it would be worth asking as some people might find this useful. Thank you for your time and work you've put in on this. I know people in open source don't hear that enough.

**Comment by amaanq** [comment]
Locals *can* accomplish this, but you're likely looking for semantic highlighting anyways which an LSP provides

**Comment by amaanq** [comment]
pyright doesn't provide semantic tokens

**Comment by amaanq** [comment]
who knows, it's closed source, you could use semshi
