### ISSUE TITLE
bug: Bad parse/behavior with docstring containing extraneous "-character

### ISSUE THREAD

**Issue by malthe** [tree-sitter/tree-sitter-python#249]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-python

### Describe the bug

An incorrect docstring with an extraneous quote to start with breaks some expectation, causing indentation to fail further down.

### Steps To Reproduce/Bad Parse Tree

If we run the repro code example, we get the following tree:
```elisp
 (class_definition class name: (identifier) :
  body: 
   (block
    (expression_statement
     (string (string_start) (string_content) (string_end)))
    (if_statement if condition: (true) : (block))
    (expression_statement
     (call function: (identifier)
      arguments: (argument_list ( ))))))
```

### Expected Behavior/Parse Tree

I expect that the `print()` statement can be correctly indented – actually, there should be exactly one possible indentation here which is one further right compared to `if True`.

### Repro

```Python
class Hello:
    """"Oh my, was that four quotes?"""

    if True:
    print()  # <- this won't indent
```

**Comment by amaanq** [comment]
Indents aren't handled here, they're likely handled by whatever editor you use. Check in with them, because that indents fine for me in Neovim
