### ISSUE TITLE
bug: Fail to parse from here but the online playground is fine

### ISSUE THREAD

**Issue by mingodad** [tree-sitter/tree-sitter-python#253]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-python

### Describe the bug

Testing this a fresh build of this repo the sample shown bellow parses fine on the online playground but fail here.

### Steps To Reproduce/Bad Parse Tree

tree-sitter parse test.py

### Expected Behavior/Parse Tree

[module](https://tree-sitter.github.io/tree-sitter/playground#) [0, 0] - [2, 0]
  [for_statement](https://tree-sitter.github.io/tree-sitter/playground#) [0, 0] - [1, 44]
    left: [identifier](https://tree-sitter.github.io/tree-sitter/playground#) [0, 4] - [0, 8]
    right: [attribute](https://tree-sitter.github.io/tree-sitter/playground#) [0, 12] - [0, 21]
      object: [identifier](https://tree-sitter.github.io/tree-sitter/playground#) [0, 12] - [0, 15]
      attribute: [identifier](https://tree-sitter.github.io/tree-sitter/playground#) [0, 16] - [0, 21]
    body: [block](https://tree-sitter.github.io/tree-sitter/playground#) [1, 2] - [1, 44]
      [expression_statement](https://tree-sitter.github.io/tree-sitter/playground#) [1, 2] - [1, 44]
        [call](https://tree-sitter.github.io/tree-sitter/playground#) [1, 2] - [1, 44]
          function: [identifier](https://tree-sitter.github.io/tree-sitter/playground#) [1, 2] - [1, 7]
          arguments: [argument_list](https://tree-sitter.github.io/tree-sitter/playground#) [1, 7] - [1, 44]
            [identifier](https://tree-sitter.github.io/tree-sitter/playground#) [1, 8] - [1, 12]
            [identifier](https://tree-sitter.github.io/tree-sitter/playground#) [1, 14] - [1, 27]
            [identifier](https://tree-sitter.github.io/tree-sitter/playground#) [1, 29] - [1, 43]

### Repro

```Python
for line in sys.stdin:
    match(line, liftoff_regex, liftoff_values)
```

**Comment by ObserverOfTime** [comment]
The playground is outdated. This happens because the parsers considers [match](https://docs.python.org/3/reference/compound_stmts.html#match) a statement.
