### ISSUE TITLE
bug: arguments in Callable not marked as types

### ISSUE THREAD

**Issue by MithicSpirit** [tree-sitter/tree-sitter-python#258]
### Did you check existing issues?

- [ ] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-python

### Describe the bug

The arguments in a `Callable` are highlighted as variables/constants rather than as types.

### Steps To Reproduce/Bad Parse Tree

See repro

### Expected Behavior/Parse Tree

The `t` should be a `@type`, but it is a `@variable` instead. If it is changed to `T`, then it is both a `@variable` and a `@constant`. Note that the `u` is correctly identified as an `@type`, and further testing suggests that the issue is the double brackets `[[`.

### Repro

```Python
f: Callable[[t], u]
```

**Comment by amaanq** [comment]
this repo is for the parser, so issues should be *parse* issues, any query/highlighting issues should be filed with the provider of that.

**Comment by MithicSpirit** [comment]
Sorry, I misunderstood the scope of this project. Either way, I still believe that the issue is present in this project. The tree (see below) shows that the `[t]` is interpreted as a type that is a list, while the `t` itself is just an identifier, when it should also be a type (like `u`).
```
(module [0, 0] - [1, 0]
  (expression_statement [0, 0] - [0, 19]
    (assignment [0, 0] - [0, 19]
      left: (identifier [0, 0] - [0, 1])
      type: (type [0, 3] - [0, 19]
        (generic_type [0, 3] - [0, 19]
          (identifier [0, 3] - [0, 11])
          (type_parameter [0, 11] - [0, 19]
            (type [0, 12] - [0, 15]
              (list [0, 12] - [0, 15]
                (identifier [0, 13] - [0, 14])))
            (type [0, 17] - [0, 18]
              (identifier [0, 17] - [0, 18]))))))))
```

**Comment by amaanq** [comment]
that's intentional, tree-sitter does not provide *semantic* info, the type is a wrapper around what rules are allowed in this construct, it could be an identifier, a list, etc.
