### ISSUE TITLE
bug: `.1l` is not valid in python2

### ISSUE THREAD

**Issue by Eloitor** [tree-sitter/tree-sitter-python#259]
### Did you check existing issues?

- [ ] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-python

### Tree-Sitter CLI Version, if relevant (output of `tree-sitter --version`)

tree-sitter 0.21.0

### Describe the bug

`.1l` or `.1L` is not valid in python2.

Test: https://github.com/tree-sitter/tree-sitter-python/blob/22d3f87bdafac2782e907330babe4af574f5d0b4/test/corpus/literals.txt#L63C1-L64

Source: https://github.com/tree-sitter/tree-sitter-python/blob/22d3f87bdafac2782e907330babe4af574f5d0b4/grammar.js#L1160

Solution: I think that changing that line to `optional(/[jJ]/)` is needed.

### Steps To Reproduce/Bad Parse Tree

1. Open python2
2. Write `.1l`

### Expected Behavior/Parse Tree

`.1l` in the test/corpus/literals.txt fails to parse.

### Repro

```Python
.1l
```

**Comment by ObserverOfTime** [comment]
Or maybe you could stop using Python 2.

**Comment by Eloitor** [comment]
It is not valid in python3 either...

**Comment by amaanq** [comment]
It's valid in python2 but not for floats
