### ISSUE TITLE
f-string contents aren't formatted

### ISSUE THREAD

**Issue by ambv** [tree-sitter/tree-sitter-python#26]
Formatted expressions in f-strings are regular Python code. They should be formatted as such.

Example done by MagicPython (opening `f"` highlighted by me):
![](https://scontent-sea1-1.xx.fbcdn.net/v/t1.0-9/30628983_2160181994008270_7970201425714085888_n.jpg?_nc_cat=0&_nc_log=1&oh=2e4f6366522b4bd5d1dc860b2eb3f70c&oe=5B74DF03)

**Comment by maxbrunsfeld** [comment]
Oh wow I had no idea python had string interpolation! Thanks for the heads up.

**Comment by ambv** [comment]
Max, can I catch you anywhere on IM so we can talk about this for a minute? I'd like to help with this.

**Comment by ambv** [comment]
I'm `@llanga` on Twitter for example.
