### ISSUE TITLE
bug: Multi-line string literal comments parsed as expression_statement instead of comment

### ISSUE THREAD

**Issue by obonyojimmy** [tree-sitter/tree-sitter-python#268]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-python

### Describe the bug

Multi-line string literal  comments parsed as `expression_statement` instead of `comment`

### Steps To Reproduce/Bad Parse Tree

1. Parse a python class definition like below:
```
class Hello:
  """
  A test hello class
  """
  def __init__(self):
     pass
```

2. The parsed Tree for Hello class body , child 0 which is expected to be a `comment` is parsed as an `expression_statement`

### Expected Behavior/Parse Tree

Would have expected a 'comment' Node , getting `expression_statement`

### Repro

```Python
# Example code that causes the issue
class Hello:
  """
  A test hello class
  """
  def __init__(self):
     pass
```

**Comment by amaanq** [comment]
Those are strings, not comments. This is expected.

**Comment by obonyojimmy** [comment]
> Those are strings, not comments. This is expected.

Thanks for the clarification
