### ISSUE TITLE
bug: TSHighlightCapturesUnderCursor empty 

### ISSUE THREAD

**Issue by EdmundsEcho** [tree-sitter/tree-sitter-python#269]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-python

### Describe the bug

When I put the mouse over a parameter, I get "No highlight groups found."

```py
def process_matrix(project_id, jid, matrix_request, derived_fields, app):
```

The tree playground generates the expected syntax tree (I see function, identifier, parameters etc...).  This suggests the parser is operating as expected.

However, there are no groups under the cursor.  This is in contrast to other languages thus suggesting a python specific parsing issue.

More generally, any guidance on how to troubleshoot this would be greatly appreciated.

Thank you!

### Steps To Reproduce/Bad Parse Tree

Put the mouse over a parameter
Call :TSHighlightCapturesUnderCursor

### Expected Behavior/Parse Tree

Tree-sitter
function_definition
identifier
parameters

### Repro

```Python
# Example code that causes the issue
def process_matrix(project_id, jid, matrix_request, derived_fields, app):
```

**Comment by amaanq** [comment]
this is the parser repo, not the repo that has the implementation of your highlighting tool (nvim-treesitter)

**Comment by EdmundsEcho** [comment]
Despite believing I configured treesitter to enabled highlighting, clearly it was not so.  

```lua
        highlight = {
            enable = true,
            additional_vim_regex_highlighting = false,
        },
```

When I call :TSEnable highlight, I get the Treesitter entry in the :Inspect message as I would expect (and the highlighting works accordingly).
