### ISSUE TITLE
Regular expressions in raw strings aren't formatted

### ISSUE THREAD

**Issue by ambv** [tree-sitter/tree-sitter-python#27]
Example formatted by MagicPython:

![](https://scontent-sea1-1.xx.fbcdn.net/v/t1.0-9/30698156_2160183627341440_1547782136168185856_n.jpg?_nc_cat=0&_nc_log=1&oh=579223f8c2d64bd3904248583e51e712&oe=5B6B0971)

**Comment by maxbrunsfeld** [comment]
/cc @queerviolet - Now we can handle this by injecting [tree-sitter-regex](https://github.com/tree-sitter/tree-sitter-regex) into raw strings. We'll have to identify the strings' raw-ness from the text, by checking if the string starts with an `r`, `fr`, or `br`.

I'm not sure how specific we want to be about our injection. Maybe we just start by doing it in all raw strings?

**Comment by stsewd** [comment]
You can write a query like https://github.com/nvim-treesitter/nvim-treesitter/blob/9e147d23566f58f2da6682242ffb89cb0de426b5/queries/python/injections.scm#L1-L6 to match nodes that contain a regex
