### ISSUE TITLE
bug: brackets, braces, and parenthesis do not highlight

### ISSUE THREAD

**Issue by j8s0n** [tree-sitter/tree-sitter-python#273]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-python

### Describe the bug

When opening a python file in nvim, most token types do not highlight properly.  After running 
```: write | edit | TSBufEnable highlight```
most of the code will highlight, but parenthesis, brackets, and braces do not still. Running `:Inspect` shows
```Treesitter                                                                                                                                                         
  - @punctuation.bracket.python links to @punctuation.bracket python ```
which looks like it's parsing properly.

### Steps To Reproduce/Bad Parse Tree

Open a python file with nvim.

### Expected Behavior/Parse Tree

Correct parsing at file open.

### Repro

```Python
# Example code that causes the issue
def foo():
  # Code that fails to parse, or causes an error
  ...
```

**Comment by amaanq** [comment]
this is the python **parser** repo and does not belong here.
