### ISSUE TITLE
bug: terminal escape sequence causes wrong indentation

### ISSUE THREAD

**Issue by Quitlox** [tree-sitter/tree-sitter-python#275]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-python

### Describe the bug

Terminal escape sequence in string causes wrong indentation.

### Steps To Reproduce/Bad Parse Tree

1. Put cursor on line with escape sequence (`<|>` denotes cursor position)
```python
_grey = "\x1b[38;20m"<|>
```
2. Hit enter

### Expected Behavior/Parse Tree

Expected:
```python
_grey = "\x1b[38;20m"
<|>
```

Actual:
```python
_grey = "\x1b[38;20m"
             <|>
```

### Repro

```Python
grey = "\x1b["
```

**Comment by ObserverOfTime** [comment]
Indentation has nothing to do with the parser.
