### ISSUE TITLE
[question] is the grammar.json written by  author of tree-sitter-python(this means author know every line's meaning), or is copy from anywhere?

### ISSUE THREAD

**Issue by liaodalin19903** [tree-sitter/tree-sitter-python#278]
### Is your feature request related to a problem? Please describe.

Hi,

When I read the  python grammar source code: tree-sitter-python,

there is the [grammar.json](https://github.com/tree-sitter/tree-sitter-python/blob/master/src/grammar.json) file, which defined the python grammar identifiers. 
it has huge content with 6000+ line JSON text.

I want to ask questions:

1、is this written by  author of tree-sitter-python(this means author know every line's meaning), or is copy from anywhere?

2、is the grammar.json every content will be used?

**Comment by almahdi404** [comment]
`grammar.json` is generated from `grammar.js`

**Comment by liaodalin19903** [comment]
> `grammar.json` is generated from `grammar.js`

@almahdi404  Could you tell me more about `grammar.js`, if every Parser (eg. tree-sitter-go, tree-sitter-rust...) have one? 
and all grammar.js are diffrent, right?

**Comment by amaanq** [comment]
Yeah, grammar.json is generated with `tree-sitter` generate (along with everything in `src` minus scanner.c)

You can read more here: https://tree-sitter.github.io/tree-sitter/creating-parsers
