### ISSUE TITLE
async and await aren't keywords

### ISSUE THREAD

**Issue by ambv** [tree-sitter/tree-sitter-python#28]
They are pseudo-keywords since Python 3.5 and actual keywords since Python 3.7. There's a lot of async/await code in the wild already. "pseudo-keyword" handling requires a bit of magic, you can see what [lib2to3's Grammar.txt](https://github.com/python/cpython/blob/master/Lib/lib2to3/Grammar.txt) is doing in the grammar for that. Look for "ASYNC" and "AWAIT" there.

Example of misformatted code:
![](https://scontent-sea1-1.xx.fbcdn.net/v/t1.0-9/30656313_2160188564007613_3530760530912346112_n.jpg?_nc_cat=0&_nc_log=1&oh=496db13fc05724bef52d70868a4b425b&oe=5B72B548)

**Comment by maxbrunsfeld** [comment]
I think they're already parsed correctly, but just not syntax highlighted in [language-python](https://github.com/atom/language-python/blob/master/grammars/tree-sitter-python.cson), unless I'm missing something.

**Comment by ambv** [comment]
OK, it's split half between language-python and tree-sitter-python. You're right that `await` has its own class and `async` in `async def` can probably be bolted on based on the entire signature getting an `async_function_definition` class. However:
* it would be nice if `async` itself had a class which would make highlighting easier to configure
* there's missing support for `async for` and `async with`, the former having a funny misformatting now in a comprenehsion

Example:
![](https://scontent-sea1-1.xx.fbcdn.net/v/t1.0-9/30652569_2160196400673496_5285655847043596288_n.jpg?_nc_cat=0&_nc_log=1&oh=3831ebc9a969e63d3f76e43a1b16c471&oe=5B591345)

**Comment by maxbrunsfeld** [comment]
Ah, I wasn't aware of `async with`; thanks for pointing that out. I'll fix the parsing of that here and add classes to the `async` and `await` tokens in `language-python`.
