### ISSUE TITLE
bug: v0.23.0 breaks `Language(tspython.language())`

### ISSUE THREAD

**Issue by jonathanhar** [tree-sitter/tree-sitter-python#280]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-python

### Describe the bug

In the new version, `tspython.language()` does nut output an integer, but rather capsule object "tree_sitter.Language"

### Steps To Reproduce/Bad Parse Tree

1. `pip install git+https://github.com/tree-sitter/tree-sitter-python.git@master`
2. Run:
```python
import tree_sitter_python as tspython
from tree_sitter import Language

PY_LANGUAGE = Language(tspython.language())
```

### Expected Behavior/Parse Tree

in v0.21.0 it would work

### Repro

```Python
# Example code that causes the issue
def foo():
  # Code that fails to parse, or causes an error
  ...
```

**Comment by almahdi404** [comment]
Check this https://github.com/tree-sitter/tree-sitter-python/commit/c3dbc7aae95ee2a2b9155637888dec62654d5ea3#diff-f1aca5f9358053e570c736ccd84ad4e75fc98048bb3bfbb16fa173d4555f48c5

See how the test works now.

Try doing like this
```rust
use tree_sitter::Parser;
use tree_sitter_python;

let mut parser = Parser::new();
parser.set_language(&tree_sitter_python::LANGUAGE.into()).expect("Error loading Python grammar");

```

**Comment by almahdi404** [comment]
The latest version of py-tree-sitter(tree-sitter) failed to be released(https://github.com/tree-sitter/py-tree-sitter/actions/runs/10562867186/job/29262209830).

Use these versions, until they publish `tree-sitter==0.23.0`
```bash
pip install tree-sitter==0.22.3 tree-sitter-python==0.21.0
```
