### ISSUE TITLE
bug: can't install 0.21.0 with pip

### ISSUE THREAD

**Issue by jordanrfrazier** [tree-sitter/tree-sitter-python#281]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-python

### Describe the bug

Some possible weirdness after 0.23.0 release? 

```
$ pip install tree-sitter-python==0.21.0
ERROR: Could not find a version that satisfies the requirement tree-sitter-python==0.21.0 (from versions: 0.23.0)
ERROR: No matching distribution found for tree-sitter-python==0.21.0
```

```
pip 24.2
Python 3.11.2
```

### Steps To Reproduce/Bad Parse Tree

1. pip install tree-sitter-python==0.21.0

### Expected Behavior/Parse Tree

install

**Comment by almahdi404** [comment]
Did you activate the Python 3.11.2 virtual env?

**Comment by jordanrfrazier** [comment]
Ah, I see that there's no wheel for arm64. https://pypi.org/project/tree-sitter-python/0.21.0/#files.

I think this was working for me prior to the 0.23.0 release though, was the arm64 binary removed from 0.21.0?

**Comment by ObserverOfTime** [comment]
It was _added_ in 0.23.0.
