### ISSUE TITLE
bug: unable to parse gnu extension syntax such as __asm

### ISSUE THREAD

**Issue by iotwq** [tree-sitter/tree-sitter-python#287]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-python

### Describe the bug

static SoftAesBlock
_encrypt(const uint8_t ix0[4], const uint8_t ix1[4], const uint8_t ix2[4], const uint8_t ix3[4])
{
    CRYPTO_ALIGN(64) uint32_t     t[4][4][256 / SOFTAES_STRIDE];
    CRYPTO_ALIGN(64) uint8_t      of[4][4];
    CRYPTO_ALIGN(64) SoftAesBlock out;
    size_t                        i;
    size_t                        j;

    for (j = 0; j < 4; j++) {
        of[j][0] = ix0[j] % SOFTAES_STRIDE;
        of[j][1] = ix1[j] % SOFTAES_STRIDE;
        of[j][2] = ix2[j] % SOFTAES_STRIDE;
        of[j][3] = ix3[j] % SOFTAES_STRIDE;
    }

#ifdef HAVE_INLINE_ASM
    __asm__ __volatile__("" : : "r"(t) : "memory");
#endif

    out.w0 = t[0][0][ix0[0] / SOFTAES_STRIDE];
    out.w0 ^= ROTL32(t[0][1][ix1[0] / SOFTAES_STRIDE], 8);
    out.w0 ^= ROTL32(t[0][2][ix2[0] / SOFTAES_STRIDE], 16);
    out.w0 ^= ROTL32(t[0][3][ix3[0] / SOFTAES_STRIDE], 24);

    return out;
}

The above function will resolve successfully by removing the following line:
__asm__ __volatile__("" : : "r"(t) : "memory");

### Steps To Reproduce/Bad Parse Tree

just read the description above

### Expected Behavior/Parse Tree

just read the description above

### Repro

```Python
# Example code that causes the issue
def foo():
  # Code that fails to parse, or causes an error
  ...
```

**Comment by amaanq** [comment]
wrong repo, not a minimal reproducible example, and no parse tree.
