### ISSUE TITLE
"in" should be handled as a keyword

### ISSUE THREAD

**Issue by ambv** [tree-sitter/tree-sitter-python#29]
Treating it as an operator (or not giving it a special class at all, as is the case in `for`) leads to poor highlighting:
![](https://scontent-sea1-1.xx.fbcdn.net/v/t1.0-9/30698068_2160188560674280_6205498916834639872_n.jpg?_nc_cat=0&_nc_log=1&oh=0641784ed01748687db5f3d9129a2ea9&oe=5B5FE778)

**Comment by maxbrunsfeld** [comment]
`in` is already highlighted as `keyword.operator`. Do you think it should have the additional classes `keyword.operator.logical` like `not`?

**Comment by ambv** [comment]
In case of `for` loops and comprehensions, `in` only receives the following scopes:
```
python
module
for_statement
```

That's going to make it tricky to highlight correctly as those are the exact same scopes that the colon gets (but the colon should be `punctuation`, see #25).

The styling you linked to is invalid for tree-sitter, the scopes that `in` receives in expression context are:
```
python
module
if_statement
comparison_operator
```

This is unfortunate because `comparison_operator` is also things like `!=`, `>`, and so on. Python users would expect `in` to be formatted exactly like `and`, `or`, and `not`. The first two are `boolean_operator` and `not` is its own `not_operator`, probably since it's unary. `in` isn't really a "booean" operator to that name wouldn't fit it. But it would do functionally.

**Comment by maxbrunsfeld** [comment]
> The styling you linked to is invalid for tree-sitter, the scopes that in receives in expression context are

No, it's valid; we can add whatever classes we want to `in` by changing that line. The `in` just doesn't show up in the `cmd-alt-p` notification because that notification only shows the syntax nodes that have been given explicit names in the grammar. The `in` is considered an *anonymous_token*.

**Comment by ambv** [comment]
Oh, so that's new with tree-sitter? How do you style anonymous tokens then?

**Comment by maxbrunsfeld** [comment]
You just put their names in quotes, like on that line I linked above.

**Comment by ambv** [comment]
Oh, but that's internal to language-python so they will never show up in Cmd+Option+P?

**Comment by ambv** [comment]
No need to apologize for the lack of documentation! I get that this is experimental. The AST approach will be way better once enabled by default. We just need to fix the remaining problems. I hope the bugs I'm reporting will be rather easy to address.

I wish there *was* a way to display classes that are used for formatting in Cmd+Option+P. I think the tree information there is good and should stay. That will help us figure out places where tree-sitter is incomplete or buggy. But for theme creators, having a section there (that would be short, as you're saying yourself) that shows what to put in the theme style would be *very* helpful. This is a much faster way to find out the currently needed class than looking at grammar CSON. Especially that this is how things *used* to work.

So, ideally we'd have "Syntax tree at cursor" (the AST nodes) and "Scopes at cursor" (the CSS classes). Currently it says the latter but it's actually the former.

**Comment by maxbrunsfeld** [comment]
> So, ideally we'd have "Syntax tree at cursor" (the AST nodes) and "Scopes at cursor" (the CSS classes). Currently it says the latter but it's actually the former.

Yeah, I think that's exactly right.

**Comment by ambv** [comment]
I guess we can close this and re-open just the "Syntax tree at cursor" vs. "Scopes at cursor" issue. But that belongs on atom/atom I guess?

**Comment by maxbrunsfeld** [comment]
Ok, I've updated `Log Cursor Scopes` to restore the old behavior; this update will ship in Atom 1.31.
