### ISSUE TITLE
bug: Certain cases interpreted as `subscript` instead of `generic_type`

### ISSUE THREAD

**Issue by JaagupAverin** [tree-sitter/tree-sitter-python#291]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-python

### Describe the bug

In certain cases where we deal with generics (such as user defined generic classes), the generics between square brackets get interpreted as a subscript as opposed to a generic.

### Steps To Reproduce/Bad Parse Tree

1. e.g in Tree-sitter playground:
```python
x: list[int] = 0
y: type[int] = int
```
2. `list[int]` is correctly classified as a `generic_type`
3. `type[int]` is incorrectly classified as `subscript`

Alternatively for similar output:
```python
class MyGeneric[T]:
	pass
    
MyAlias = MyGeneric[int]
```

### Expected Behavior/Parse Tree

Both cases should be `generic_type`s.

**Comment by amaanq** [comment]
The first case is definitely solvable, but the second case not so much, because it's truly ambiguous as to whether or not it's a subscript or a generic type. That would require semantic information about the code, which is typically something an interpreter/compiler/LSP does, and not tree-sitter
