### ISSUE TITLE
Implicit narrowing in serialize might be problematic

### ISSUE THREAD

**Issue by typesanitizer** [tree-sitter/tree-sitter-python#41]
I created this issue https://github.com/tree-sitter/tree-sitter-agda/issues/2 -- I just realized that the code there is based off the code here, so you have the same issue (`uint16_t` gets narrowed to `char`):

https://github.com/tree-sitter/tree-sitter-python/blob/a954c045cd5576c1c610b8318a638ef4b471ab0f/src/scanner.cc#L100-L106

I submitted a PR there to fix the wraparound due to narrowing -- would you like me to do the same here?

On a related note, I noticed this commit https://github.com/tree-sitter/tree-sitter-python/commit/250cc7863b34b725b0aacc6c6bf35bbbdcadcca3 where you clamp the length of delimiter stack -- isn't that a logic error (because you're throwing away delimiters)? Is it that you expect that limit to never be reached in a practical situation, so you've written it this way to keep the code simple?

**Comment by amaanq** [comment]
The narrowing has been fixed, see https://github.com/tree-sitter/tree-sitter-python/issues/207, it did indeed cause a logic bug in rare cases

Now it is explicitly converted
