### ISSUE TITLE
Error with BOM

### ISSUE THREAD

**Issue by calixteman** [tree-sitter/tree-sitter-python#48]
There is a parsing error for a file beginning with a bom (\uFEFF).
What's weird here is that it should be handled correctly because \uFEFF appears in the extras list.

**Comment by maxbrunsfeld** [comment]
Tree-sitter should really be hard-coded to skip BOMs. I'll look into this when I get a chance.

**Comment by maxbrunsfeld** [comment]
This is fixed in the latest Tree-sitter.
