### ISSUE TITLE
# inside f-string interpolation breaks parsing

### ISSUE THREAD

**Issue by EvgeniyPeshkov** [tree-sitter/tree-sitter-python#49]
Parser cannot handle expressions like this:
```
value = 1234
print(f'input={value:#06x}')
```

**Comment by lgeiger** [comment]
@maxbrunsfeld Could you take a look?
This also break syntax highlighting in Atom 1.40.1, since the characters after `#` are interpreted as an inline comment. So it would be great to get a fix into Atom as well.
