### ISSUE TITLE
Detect placeholders in pre-formatted strings

### ISSUE THREAD

**Issue by chbk** [tree-sitter/tree-sitter-python#51]
I would love it if Tree-sitter handled placeholders in regular strings:

```python
'My name is %12s' % 'Slim Shady'
'My name is %(name)12s' % {'name': 'Slim Shady'}
'My name is {:>12}'.format('Slim Shady')
'My name is {name:>12}'.format(name='Slim Shady')
'My name is {names[0]:>12}'.format(names=['Slim Shady'])
```

More examples:
https://pyformat.info

MagicPython output with Atom's One Dark theme:
![s](https://user-images.githubusercontent.com/7478535/64600853-220b7780-d3bc-11e9-8248-0bc2d2553e51.png)

**Comment by somebody1234** [comment]
sounds ok, but not 100% sure this is a good idea, there's a small chance it could be a regular string. then again, #27 is a similar issue

**Comment by stsewd** [comment]
I think this could be possible with an injection (contrary to support this in the grammar itself). So we would need to write a small grammar for the string placeholders, the queries to detect were to inject it should be easy.
