### ISSUE TITLE
Support full range of Unicode characters for identifiers specified in Python language reference

### ISSUE THREAD

**Issue by lee-dohm** [tree-sitter/tree-sitter-python#53]
Python v3 supports a wide variety of Unicode character classes in identifiers. The grammar definition should support [the same sets as specified](https://docs.python.org/3.7/reference/lexical_analysis.html#identifiers).

**Comment by patrickt** [comment]
I think @maxbrunsfeld filed an issue about making it easier to refer to specific classes of Unicode characters, though I can’t find it now. That would probably be the more holistic way of doing things. We also need this for tree-sitter-go, which went all wobbly when presented with an `EXTENDED ARABIC-INDIC DIGIT ZERO` in an identifier.

**Comment by lee-dohm** [comment]
Thanks @patrickt. It looks like this is the issue you're referencing? https://github.com/tree-sitter/tree-sitter/issues/95

**Comment by patrickt** [comment]
Yeah, that’s it!
