### ISSUE TITLE
No scopes for built-in types

### ISSUE THREAD

**Issue by chbk** [tree-sitter/tree-sitter-python#55]
Tree-sitter-python doesn't provide scopes for built-in types like [Tree-sitter-java](https://github.com/tree-sitter/tree-sitter-java/blob/acc60fc4978be97cefbf567d71dd98b8da4388ff/src/grammar.json#L6370).

Built-in types are: `bool`, `bytearray`, `bytes`, `complex`, `dict`, `float`, `frozenset`, `int`, `list`, `memoryview`, `object`, `range`, `set`, `str`, `tuple`.

[Documentation](https://docs.python.org/3/library/stdtypes.html).

**Comment by patrickt** [comment]
I think this is intentional, as unlike Java, the names of built-in types can be overridden, so there’s no way to know that an occurrence of `str` necessarily refers to the Python `str`.
