### ISSUE TITLE
Why is C++ used rather than C

### ISSUE THREAD

**Issue by mcobzarenco** [tree-sitter/tree-sitter-python#60]
Compared to most other tree sitter grammars, the Python one uses C++, i. e. `scanner.cc` which makes it much harder to use (because of the requirements to link the application with libstdc++) . I haven't managed to get it working using the Rust bindings on stable. Is there a good reason? It contradicts one of stared goals of tree sitter:

 > Dependency-free so that the runtime library (which is written in pure C) can be embedded in any application

**Comment by maxbrunsfeld** [comment]
I use it from Rust myself and have found it painless, since libc++/libstdc++ is available in almost every environment where a C compiler is available. C++ is also used in external scanners of other languages.

In the case of that file, we use C++ because of std::vector and std::string.

**Comment by mcobzarenco** [comment]
Thanks for this @maxbrunsfeld , would you mind sharing your `build.rs` that links with `libstdc++`? Have you tried linking statically (`musl`  needs some shimming as it doesn't support C++ out of the box)? On nightly, the following build directive is useful, but still won't just work:
```
println!("cargo:rustc-link-lib=static=stdc++");
```

**Comment by maxbrunsfeld** [comment]
Did you try the [cpp](https://docs.rs/cc/1.0.47/cc/struct.Build.html#method.cpp) method? It should just work.

**Comment by mcobzarenco** [comment]
Ha! Thanks for that, it does help set up the env for dynlib case (static linking against C++ still requires recompiling libstd++ against musl, I [think](https://www.musl-libc.org/faq.html)).

However, it seems that compiling `parser.c` with a C++ compiler rather than C doesn't work
```
...
cargo:warning=grammars/tree-sitter-python/src/parser.c:40434:3: sorry, unimplemented: non-trivial designated initializers not supported
cargo:warning=grammars/tree-sitter-python/src/parser.c:40434:3: sorry, unimplemented: non-trivial designated initializers not supported
cargo:warning=grammars/tree-sitter-python/src/parser.c:40434:3: sorry, unimplemented: non-trivial designated initializers not supported
cargo:warning=grammars/tree-sitter-python/src/parser.c:40434:3: sorry, unimplemented: non-trivial designated initializers not supported
...
````

This seems to be as `parser.c` uses [designated initializers syntax](http://gcc.gnu.org/onlinedocs/gcc/Designated-Inits.html) (i.e. `.field = value`) which is [not valid C++](https://en.cppreference.com/w/cpp/language/aggregate_initialization) according to the standard:

 > Note: out-of-order designated initialization, nested designated initialization, mixing of designated initializers and regular initializers, and designated initialization of arrays are all supported in the C

**Comment by maxbrunsfeld** [comment]
Yeah, I think you need a c build and a C++ build.

**Comment by mcobzarenco** [comment]
Gotcha, makes sense -- I got it to work, thank you for the help.

**Comment by mcobzarenco** [comment]
FWIW, using C++ does seem to preclude static linking using musl

**Comment by maxbrunsfeld** [comment]
Yeah, if you're trying to avoid dependencies on libc/libc++, I can see how this would complicate things.

One reference I might use is [Emscripten](https://github.com/emscripten-core/emscripten), which compiles code written in both C **and C++** into self-contained WebAssembly bindings using [mostly-unmodified source files from libc++](https://github.com/emscripten-core/emscripten/tree/incoming/system/lib/libcxx). 

I think that you could probably use the same approach to create a statically-linked native binary, by adding several source files and include flags from libc++ to your build.
