### ISSUE TITLE
Tree Structure is not coming right

### ISSUE THREAD

**Issue by anandsork** [tree-sitter/tree-sitter-python#61]
I am trying to get the tree for following code.
`get_data_dir() + os.path.sep`

Ideally I excpect that there will be a binary_expression/operator at the start. Then Left side will be call and right side would be attribute.

However, the structure is coming as follows. I feel that it is wrong. 
Can somebody tell me how I could able to get the correct tree structure? (I changed the code to "Javascript" and the structure came correct. So I think there is something wrong with python-parser)
```
module [0, 0] - [1, 0])
  expression_statement [0, 0] - [0, 28])
    attribute [0, 0] - [0, 28])
      object: attribute [0, 0] - [0, 24])
        object: binary_operator [0, 0] - [0, 19])
          left: call [0, 0] - [0, 14])
            function: identifier [0, 0] - [0, 12])
            arguments: argument_list [0, 12] - [0, 14])
          right: identifier [0, 17] - [0, 19])
        attribute: identifier [0, 20] - [0, 24])
      attribute: identifier [0, 25] - [0, 28])
```

**Comment by maxbrunsfeld** [comment]
Wow, that was very wrong. Thank you for the report! Fixed on master.

**Comment by maxbrunsfeld** [comment]
The new parser is up on the web playground.

**Comment by anandsork** [comment]
Thanks for the prompt fix. Now looks correct on playground. 
I shall build the library and test. I shall report back, in case I see any issues.
