### ISSUE TITLE
Python parsing does not work well with empty blocks

### ISSUE THREAD

**Issue by mgsloan** [tree-sitter/tree-sitter-python#64]
In the playground, if I type in

```python
def foo():
```

I get

```
module [0, 0] - [1, 0])
  ERROR [0, 0] - [0, 10])
    identifier [0, 4] - [0, 7])
    parameters [0, 7] - [0, 9])
```

If I add a statement at indent level 0:

```python
def foo():

print "hi"
```

I get

```
module [0, 0] - [3, 0])
  function_definition [0, 0] - [2, 10])
    name: identifier [0, 4] - [0, 7])
    parameters: parameters [0, 7] - [0, 9])
    body: block [2, 0] - [2, 10])
      print_statement [2, 0] - [2, 10])
        argument: string [2, 6] - [2, 10])
```

I believe this reveals a flaw in the indentation sensitivity of the python parser.  Ideally:

1. `print "hi"` should not get parsed as a child of the `function_definition`.

2. The empty block should be filled in with a `MISSING` recovery of insertion of `pass`

I don't know much about tree sitter grammar construction, so I am not sure if fixing this is feasible.  Similar issues occur with unterminated parenthesis at the end of the block, incomplete infix operators, etc.

**Comment by maxbrunsfeld** [comment]
Thanks for writing this up!

**Comment by mgsloan** [comment]
You're welcome, thanks for the quick fix!
