### ISSUE TITLE
Lack of body does not cause error

### ISSUE THREAD

**Issue by acbart** [tree-sitter/tree-sitter-python#67]
Trying out the [Python playground](https://tree-sitter.github.io/tree-sitter/playground), I entered this code:

```python
def foo():
```

And got this result:

```
module [0, 0] - [1, 0])
  function_definition [0, 0] - [0, 10])
    name: identifier [0, 4] - [0, 7])
    parameters: parameters [0, 7] - [0, 9])
    body: block [0, 10] - [0, 10])
```

Even though not having a body in a function is a syntax error in Python 3. Perhaps this is related to the error construction behavior, and I misunderstand how Tree-Sitter works, but it seems to me like there should be an error node in there.

**Comment by patrickt** [comment]
I believe this is intentional, viz. https://github.com/tree-sitter/tree-sitter-python/pull/65.

**Comment by acbart** [comment]
Oh, well that's a little strange to me. Since I need accurate parse trees, I suppose that means this won't meet my needs. Ah well.
