### ISSUE TITLE
except_clause no except_item

### ISSUE THREAD

**Issue by gilosh** [tree-sitter/tree-sitter-python#70]
For the following code:

```
try:
  pass
except Exception as e:
  pass
```
```
...   except_clause )
        identifier )
        identifier )
        block ) ...
```

It would be helpful to have an 'except_item' similarly to 'with_item', helping distinguish between the identifiers:
```
    with_item )
      value: identifier )
      alias: identifier )

.. # suggestion
    except_item )
      value: identifier )
      alias: identifier )
```

**Comment by maxbrunsfeld** [comment]
I think `except_item` isn't needed as clearly as `with_item`, because unlike `with_item`, there can only be one of them in each `except_clause`.

I'm still open to this change though. Alternatively, should we just put a `value` and `alias` fields in `except_clause`?

**Comment by gilosh** [comment]
Right! I was under the wrong assumption you could have multiple exceptions (I should have double checked with the interpreter).

1. Would you say that this is a bug then?
```
try:
  pass
except RuntimeError, TypeError:
  pass
```
```
  try_statement [0, 0] - [3, 6])
...
    except_clause [2, 0] - [3, 6])
      identifier [2, 7] - [2, 19])
      identifier [2, 21] - [2, 30])
      block [3, 2] - [3, 6])
...
```
CPython
```
  File "<stdin>", line 3
    except RuntimeError, TypeError:
```

2. Your solution for adding the fields sounds perfect

**Comment by amaanq** [comment]
The reason that's accepted is because it's valid in Python 2
