### ISSUE TITLE
Docstrings not recognized

### ISSUE THREAD

**Issue by chbk** [tree-sitter/tree-sitter-python#77]
[PEP 257](https://www.python.org/dev/peps/pep-0257/#what-is-a-docstring)

> A docstring is a string literal that occurs as the first statement in a module, function, class, or method definition.

Can this be incorporated into the grammar?

**Comment by maxbrunsfeld** [comment]
Designating a string as "a docstring" is not something that'll be done at the level of the parser. It's part of the *semantics* of the python runtime, but it isn't special syntax. So I don't think we'll make changes to how docstrings are represented in the syntax tree.

**Comment by samuela** [comment]
Is there a [query](https://tree-sitter.github.io/tree-sitter/using-parsers#pattern-matching-with-queries) that could identify class docstrings effectively? I've been poking around a bit, but have not been able to get something to work yet.

**Comment by ObserverOfTime** [comment]
https://github.com/nvim-treesitter/nvim-treesitter/blob/cf7baac/queries/python/highlights.scm#L229-L234
