### ISSUE TITLE
Escaping of curly braces inside f-strings causes parsing to fail

### ISSUE THREAD

**Issue by eugmes** [tree-sitter/tree-sitter-python#79]
The following valid python code fails to parse:

```python
def test():
    s = f'{{'
    x = 'test'
    return s + x
```

Atom incorrectly highlights `x = ` as a string.

**Comment by stsewd** [comment]
I think this was fixed by https://github.com/tree-sitter/tree-sitter-python/pull/128. I'll check tomorrow if the given example is parsed correctly now.

**Comment by stsewd** [comment]
yep, this is already fixed.

**Comment by maxbrunsfeld** [comment]
Thanks @stsewd!
