### ISSUE TITLE
Could not identify python docstring?

### ISSUE THREAD

**Issue by Ceceu** [tree-sitter/tree-sitter-python#80]
Using the following code snippet in [Syntax Tree Playground](https://tree-sitter.github.io/tree-sitter/playground)

```python
def get_vid_from_url(url):
        """
        Extracts video ID from URL.
        """
        return match(url, r'youtu\.be/([^?/]+)')
```

the resulting tree fails to identify `Extracts video ID from URL.` as docstring.

**Comment by patrickt** [comment]
We don’t currently give the docstring a field name. I’m not sure whether this would be worth doing, as it is perhaps the job of the query API.

**Comment by maxbrunsfeld** [comment]
Yeah, I think this is best handled outside of the parser itself. As far as the parser is concerned, the docstring is just a string. It is a higher layer of logic that identifies the first string in a definition block as "the docstring".
