### ISSUE TITLE
Add a ReturnStatement node for lambdas

### ISSUE THREAD

**Issue by Luni-4** [tree-sitter/tree-sitter-python#92]
It would be helpful to add a `ReturnStatement` node for lambdas

**Comment by maxbrunsfeld** [comment]
Can you give an example of source code, the current parse tree, and the expected parse tree that you're proposing?

**Comment by Luni-4** [comment]
Initially, I wanted to count the exit points of a lambda, but since Python states that a lambda always returns an expression, my problem could be solved counting the single lambdas, even for the nested case:

`bar = lambda a: lambda b: b or True or True`

I cannot think a more difficult case, so we can close this issue.
