### ISSUE TITLE
Should expression be a subtype of expression_statement instead of a child?

### ISSUE THREAD

**Issue by andycraig** [tree-sitter/tree-sitter-python#94]
In `grammar.js`, `expression` is a `choice` of `expression_statement`: https://github.com/tree-sitter/tree-sitter-python/blob/master/grammar.js#L183-L184

In `node-types.json`, `expression` is a child of `expression_statement`: https://github.com/tree-sitter/tree-sitter-python/blob/master/src/node-types.json#L1164-L1182

Is this correct? Since `expression` is a `choice` of `expression_statement`, I would have expected `expression` to be a _subtype_ of `expression_statement` in `node-types.json`, not a child.

(I'm interested in this because I want to identify nodes that are valid (syntactically correct) Python by themselves so that I can send them to a REPL. My method for doing this is to check whether they are subtypes of `_compound_statement` or `_simple_statement`. But this breaks down for `expression_statement`, which has children instead of subtypes.)

Thank you for making tree-sitter-python!

EDIT: Fixed link.

**Comment by somebody1234** [comment]
:/ you linked the same thing twice

**Comment by somebody1234** [comment]
also note that [`node-types.json` is generated](https://github.com/tree-sitter/tree-sitter/blob/ff488f89c93aad767b46c4fe08a20e5fd26b54dc/cli/src/generate/mod.rs#L90) (from `grammar.js`)

**Comment by somebody1234** [comment]
i'm guessing what you probably mean then is, should `expression_statement` be a [supertype](https://github.com/tree-sitter/tree-sitter-python/blob/c4282ba411d990d313c5f8e7850bcaaf46fbf7da/grammar.js#L40)

**Comment by andycraig** [comment]
Hi @somebody1234, thank you for your reply. I think I may have misunderstood how subtypes and children work. I thought that subtypes generally corresponded to `choice`, but reading the docs again I see that they correspond to supertypes.

It sounds like adding `expression_statement` as a supertype would resolve this particular case but I'd probably need the same thing to be done for lots of different node types (across multiple languages too, as I'm aiming for this to be language-independent). So I think what I actually need to do is modify my algorithm to identify child nodes corresponding to `choice`.

**Comment by maxbrunsfeld** [comment]
Conceptually, I don't think that an `expression` is a subtype of an `expression_statement`. In my mind, statements and expressions are two distinct categories of nodes. An `expression_statement` is a simple type of statement, which contains an expression (or an assignment, which can't occur as a normal expression).

**Comment by andycraig** [comment]
Hi @maxbrunsfeld, it sounds like my concept of subtypes and supertypes in the context of Tree-sitter was not correct. Thank you for clarifying. I will close this issue.
