### ISSUE TITLE
Comments at the ends of an indented block are parsed as if they're outside the block

### ISSUE THREAD

**Issue by hponde** [tree-sitter/tree-sitter-python#97]
For example:

```
def foo():
    """some
    docstring
    string""""
    # comment
```

Will parse a function node that terminates in the docstring.

**Comment by orph** [comment]
To clarify, given the following code, the `function_definition` node will end after the docstring and not include the rest of the body:

```
def foo():
    """some
    docstring
    string""""
    # comment
    return 1+1
```

**Comment by maxbrunsfeld** [comment]
@orph Your code example does not trigger a bug. For that snippet, I get a correct syntax tree:

```sh
$ tree-sitter parse test.py
(module [0, 0] - [6, 0]
  (function_definition [0, 0] - [5, 14]
    name: (identifier [0, 4] - [0, 7])
    parameters: (parameters [0, 7] - [0, 9])
    body: (block [1, 4] - [5, 14]
      (expression_statement [1, 4] - [3, 13]
        (string [1, 4] - [3, 13]))
      (comment [4, 4] - [4, 13])
      (return_statement [5, 4] - [5, 14]
        (binary_operator [5, 11] - [5, 14]
          left: (integer [5, 11] - [5, 12])
          right: (integer [5, 13] - [5, 14]))))))
```

The bug is specific to *comments* appearing at the end of an indented block. In that situation, the comments will be parsed as if they are *outside* the block.

**Comment by orph** [comment]
@maxbrunsfeld Ahh of course. The issue is because we're progressively loading as new bytes come over the network and stopping when the function ends, which occurs when we add the comment bytes. 

Please disregard my comment, the original comment is the underlying issue.
